config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :artists
  resources :gallery_submissions
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :exhibitions
  resources :charges
  resources :cities
  resources :purchases, only: [:show]
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :item_arts

  root 'pages#home'

  get 'about' => 'pages#about'

  get 'login' => 'pages#login'

  get 'signup' => 'pages#signup'

  get '/settings' => 'pages#settings', as: 'settings'

  get '/how_it_works' => 'pages#how_it_works', as: 'how_it_works'

  get '/affiliates' => 'affiliates#landing_page', as: 'affiliate_landing_page'

  get 'initiate_trial_subscription' => 'subscriptions#initiate_subscription'

  get 'welcome' => 'pages#user_welcome'

  get 'work/new' => 'item_arts#new_work', as: 'new_work'

  get 'balance' => 'pages#balance_payments', as: 'balance_payments'

  get '/dashboard/sales' => 'pages#sales', as: 'sales'

  get 'dashboard/artists' => 'pages#artists', as: 'gallery_artists'

  get 'billing' => 'billing#billing_information', as: 'billing_information'

  get '/:search_code' => 'item_arts#direct_link', as: 'direct_link_to_item_art'

  get '/signup/affiliates' => 'pages#signup_for_affiliates', as: 'signup_for_affiliates'

  get '/signup/galleries' => 'pages#signup_for_galleries', as: 'signup_for_galleries'

  get '/login/affiliates' => 'pages#login_for_affiliates', as: 'login_for_affiliates'

  get '/affiliates/settings' => 'affiliates#settings', as: 'settings_for_affiliates'

  get '/affiliates/payouts' => 'affiliates#payouts', as: 'affiliate_payouts'

  get '/affiliates/dashboard' => 'affiliates#dashboard', as: 'affiliate_dashboard'

  get '/dashboard/messages' => 'pages#messages', as: 'inbox'

  get 'views' => 'pages#views'

  get 'my_purchases' => 'pages#purchases'

  get '/dashboard/settings/accounts' => 'pages#payment_settings', as: 'payment_settings'

  get '/dashboard/settings/payments' => 'pages#customer_payment_settings', as: 'customer_payments'

  get '/dashboard/settings/bank_accounts' => 'pages#bank_accounts', as: 'bank_accounts'

  get 'item_search' => 'item_arts#search'

  post 'setup_user' => "pages#setup_user"

  get 'dashboard/works' => 'pages#my_work', as: 'works'

  get 'dashboard/shows' => 'pages#shows', as: 'dashboard_shows'

  get 'dashboard/engagement' => 'pages#engagement', as: 'engagement'

  post 'update_stripe_account' => 'pages#update_stripe_account'

  post 'update_bank_account' => 'pages#update_bank_account'

  post 'new_bank_account' => 'pages#new_bank_account'

  post '/order/start/create_customer' => 'charges#create_customer', as: 'create_customer'

  post '/home_page/question' => 'pages#question', as: 'question'

  get '/setup/gallery' => 'galleries#inital_create', as: 'gallery_inital_create'

  get '/setup/schedule_call' => 'pages#schedule_setup_call', as: 'schedule_setup_call'

  get '/setup/get_started' => 'pages#get_started', as: 'get_started'

  post '/setup/schedule_call/save' => 'pages#save_setup_call', as: 'save_setup_call'

  post '/setup/gallery/create' => 'galleries#create_for_user', as: 'create_gallery_for_user'

  post '/stripe/webhook/artyam' => 'stripe#webhook', as: 'stripe_webhook'

  get 'item_art/mark_as_sold/:itemID' => 'item_arts#mark_as_sold', as: 'mark_as_sold'

  post '/order/update_contact/:order_id/' => 'charges#update_contact_information', as: 'update_contact_for_order'

  post '/billing/initialize' => 'billing#initiate', as: 'billing_initialize'

  post '/payments/new' => 'purchases#new_card', as: 'new_card'

  post '/submission/:submission_id/checkout' => 'purchases#submission_checkout', as: 'submission_checkout'

  get '/checkout/success/:purchase_id' => 'purchases#checkout_success', as: 'checkout_success'

  post 'email/item/:item_art_id' => 'pages#email_to_me', as: 'email_to_me'

  get 'payments/default/new/:card_id' => 'purchases#new_default_card', as: 'new_default_card'
  
  get 'payments/default/delete/:card_id' => 'purchases#delete_card', as: 'delete_card'
  
  get 'accounts/default/new/:card_id' => 'purchases#new_default_account', as: 'new_default_account'
  
  get 'accounts/delete/:card_id' => 'purchases#delete_account', as: 'delete_account'
  
  get 'artwork/new/add_details/:id' => 'item_arts#detail_form', as: 'item_art_detail_form'
  

  get 'artist/:name' => 'artists#profile', as: 'artist_profile'

  get 'artist/:name/about' => 'artists#profile_about', as: 'artist_profile_about'

  get 'artist/:name/shows' => 'artists#profile_shows', as: 'artist_profile_shows'

  get 'gallery/:name' => 'galleries#profile', as: 'gallery_profile'

  get 'gallery/:name/shows' => 'galleries#profile_shows', as: 'gallery_profile_shows'

  get 'gallery/:name/about' => 'galleries#profile_about', as: 'gallery_profile_about'

  get 'show/:name' => 'shows#profile', as: 'show_profile'

  get 'blog/selling-your-art-in-cafes-restaurants-and-more' => 'blog#selling_your_art', as: 'selling_your_art'
  

  get '/:display_name/about' => 'pages#profile_about', as: 'profile_about'

  get '/work/recently_viewed' => 'pages#recently_viewed', as: 'recently_viewed_work'

  post '/order/start' => 'charges#start_checkout', as: 'start_checkout'

  get '/order/:order_id/payment' => 'charges#start_order', as: 'start_order'

  get '/order/:order_id/contact' => 'charges#add_contact_information', as: 'add_contact_information_to_order'

  get '/purchase/:purchase_id/confirmation' => 'purchases#confirmation', as: 'purchase_confirmation'

  get 'order/:order_id/confirm' => 'charges#confirm_order', as: 'confirm_order'

  post 'order/:order_id/confirm/purchase' => 'charges#confirm_purchase', as: 'confirm_purchase'

  post 'submission/:submission_id/collection/create' => 'gallery_submissions#create_collection', as: 'create_collection'

  get 'submission/:submission_id/confirm' => 'gallery_submissions#confirm_submission', as: 'confirm_submission'

  get 'submissions/select_gallery' => 'gallery_submissions#select_gallery', as: 'select_gallery'

  get 'gallery/submission/format/:id/new' => 'galleries#submission_format', as: 'gallery_submission_format'

  get 'gallery/submission/format/save' => 'galleries#submission_format_save', as: 'gallery_submission_formats'
  
  get 'gallery/submission/setup/:gallery_id' => 'gallery_submissions#setup', as: 'gallery_submission_setup'

end

app/models/artist.rb
class Artist < ActiveRecord::Base


	belongs_to :user

	belongs_to :gallery

	has_many :item_arts

	has_many :shows
	
	has_attached_file :image, 
	:styles => { :medium => "100x100#", :small => "70x70#", :thumb => "30x30#"},
	:default_url => 'missing_person_photo.png',
	:s3_protocol => :https

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


	def more_work(item, count)

    	return self.item_arts.where.not(id: item).last(count)

  	end


  	def related_artists
  		
  		@artists = Artist.all.where.not(id: self.id)

  		return @artists.last(3)

  	end


end

app/controllers/artists_controller.rb
class ArtistsController < InheritedResources::Base

	def new


		@return_home_only = true

        @page_title = "New Artist"

        @form_header_prompt = "Enter Artist Information"

        @artist = Artist.new

	end

	
	def profile

		@artist = Artist.where(:name => params[:name]).last


	end

	def profile_about

		@artist = Artist.where(:name => params[:name]).last


	end

	def profile_shows

		@artist = Artist.where(:name => params[:name]).last


	end



	def create
    
	    if user_signed_in?

	      @artist = Artist.new(artist_params)

	      if current_user.is_gallery

	      	if current_user.galleries.count == 1
	      		@artist.update(:is_user => false, :gallery_id => current_user.galleries.last.id)
	      	end

	      elsif current_user.is_artist

	      	@artist.update(:user_id => current_user.id, :is_user => true)

	      end


	      respond_to do |format|
	        if @artist.save
	          format.html { redirect_to gallery_artists_path, notice: 'Artist successfully saved.' }
	          format.json { render :show, status: :created, location: @artist }
	        else
	          format.html { render :new }
	          format.json { render json: @artist.errors, status: :unprocessable_entity }
	        end
	      end

	    else

	      redirect_to root_path
	    end

  	end


  private

    def artist_params
      params.require(:artist).permit(:name, :biography, :artist_statement, :birth_year, :nationality, :image)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<div class="form-container">

  <h4><%= @form_header_prompt %></h4>

  <%= form_for(@artist) do |f| %>
    <% if @artist.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

        <ul>
        <% @artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">

      <label>Artist Photo</label><br>
      
      <span>
      
        <%= image_tag @artist.image.url, class: "item-art-medium-image" %>
        <br>
        <%= f.file_field :image, class: "form-control" %>

      </span>

    </div>

    <div class="field">
      <%= f.label :biography %><br>
      <%= f.text_area :biography %>
    </div>

    <div class="field">
      <%= f.label :artist_statement %><br>
      <%= f.text_area :artist_statement %>
    </div>

    <div class="field">
      <%= f.label :birth_year %><br>
      <%= f.text_field :birth_year %>
    </div>

    <div class="field">
      <%= f.label :nationality %><br>
      <%= f.text_field :nationality %>
    </div>

    <div class="actions">
      <%= f.submit "Save New Artist", class:"button large black-background" %>
    </div>

    
  <% end %>


</div>

app/views/artists/_index_grid.html.erb
<div class="image-grid">

	<% artists.each do |artist| %>

		<div class="entry <% if image_only %>image-only<%end%><% if columns == 2 %>col-2<%end%>">
			
			<% if user_signed_in? %>

				<div class="image-container">
					
					<%= link_to(artist_profile_path(artist.name)) do %>
						<%= image_tag artist.image.url, class: "grid-image"%>
					<% end %>

				</div>

			<%else%>

				<div class="image-container">

					<%= link_to(artist_profile_path(artist.name)) do %>

						<%= image_tag artist.image.url, class: "grid-image"%>

					<% end %>

				</div>

			<%end%>
			
				
			<% unless image_only %>

				<div class="detail-container">

					<a href="<%= artist_profile_path(artist.name) %>" class="artwork-metadata artist-name"><%= artist.name %></a>
					<br>

					<a href="<%= artist_profile_path(artist.name) %>" class="artwork-metadata"><b>Artworks:</b> <%= artist.item_arts.count %></a>
					<br>

		    	</div>

	    	<%end%>

		</div>

	<% end %>

</div>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Biography</th>
      <th>Artist statement</th>
      <th>Birth year</th>
      <th>Nationality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.biography %></td>
        <td><%= artist.artist_statement %></td>
        <td><%= artist.birth_year %></td>
        <td><%= artist.nationality %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<div class="content">

	<%= render 'form' %>

</div>

app/views/artists/profile.html.erb
<!-- <p>
  <strong>Biography:</strong>
  <%# @artist.biography %>
</p>

<p>
  <strong>Artist statement:</strong>
  <%# @artist.artist_statement %>
</p> -->


<div class="open-page-container">

  <div class="profile-header">

    <div class="profile-header-content">

        <%= image_tag @artist.image.url(:medium), class: "medium-profile-image"%>

        <br>

        <h2><%= @artist.name %></h2>

        <p><%= @artist.nationality %>, b. <%= @artist.birth_year %></p>

    </div>

  </div>

  <div class="profile-content">

    <div class="section-header-nav">

      <ul>
        <li><a class="active" href="<%= artist_profile_path(@artist.name) %>" class="click-to-reveal active">Works</a></li><li><a href="<%= artist_profile_about_path(@artist.name) %>">About</a></li><li><a href="<%= artist_profile_shows_path(@artist.name) %>">Shows</a></li>
      </ul>

    </div>

    <div id="works">

      <% if @artist.item_arts.count > 0 %>

        <%= render :partial => 'item_arts/index_grid', :locals => {:items => @artist.item_arts.reverse, :image_only => false, :columns => 3} %>

      <%else%>

        <div class="nothing-to-see-container">

          <p class="red">

            <% if user_signed_in?%>

              <% if current_user.galleries.last.id == @artist.gallery_id %>

                You have not shared any artwork yet. <%= link_to "Add Artwork", new_item_art_path, class: "warning-text-cta" %>

              <%else%>

                <%= @artist.name %> has not shared any artwork yet.

              <%end%>

            <%else%>

              <%= @artist.name %> has not shared any artwork yet.

            <%end%>

          </p>

        </div>


      <%end%>

    </div>

  </div>

</div>

app/views/artists/profile_about.html.erb
<!-- <p>
  <strong>Biography:</strong>
  <%# @artist.biography %>
</p>

<p>
  <strong>Artist statement:</strong>
  <%# @artist.artist_statement %>
</p> -->


<div class="open-page-container">

  <div class="profile-header">

    <div class="profile-header-content">

        <%= image_tag @artist.image.url(:medium), class: "medium-profile-image"%>

        <br>

        <h2><%= @artist.name %></h2>

        <p><%= @artist.nationality %>, b. <%= @artist.birth_year %></p>

    </div>

  </div>

  <div class="profile-content">

    <div class="section-header-nav">

      <ul>
        <li><a href="<%= artist_profile_path(@artist.name) %>" class="click-to-reveal">Works</a></li><li><a class="active" href="<%= artist_profile_about_path(@artist.name) %>">About</a></li><li><a href="<%= artist_profile_shows_path(@artist.name) %>">Shows</a></li>
      </ul>

    </div>


    <div class="reveal-panel" id="about">
      


      <% if @artist.biography %>

        <div class="sub-section">

          <h4>Biography</h4>

          <p><%= @artist.biography %></p>

        </div>

      <%end%>

      <% if @artist.artist_statement %>
        
        <div class="sub-section">

          <h4>Artist Statement</h4>

          <p><%= @artist.artist_statement %></p>

        </div>

      <%end%>


    </div>

  </div>

</div>

app/views/artists/profile_shows.html.erb
<!-- <p>
  <strong>Biography:</strong>
  <%# @artist.biography %>
</p>

<p>
  <strong>Artist statement:</strong>
  <%# @artist.artist_statement %>
</p> -->


<div class="open-page-container">

  <div class="profile-header">

    <div class="profile-header-content">

        <%= image_tag @artist.image.url(:medium), class: "medium-profile-image"%>

        <br>

        <h2><%= @artist.name %></h2>

        <p><%= @artist.nationality %>, b. <%= @artist.birth_year %></p>

    </div>

  </div>

  <div class="profile-content">

    <div class="section-header-nav">

      <ul>
        <li><a href="<%= artist_profile_path(@artist.name) %>" class="click-to-reveal">Works</a></li><li><a href="<%= artist_profile_about_path(@artist.name) %>">About</a></li><li><a class="active" href="<%= artist_profile_shows_path(@artist.name) %>">Shows</a></li>
      </ul>

    </div>


    <div class="reveal-panel" id="shows">
      <% if @artist.shows.count > 0 %>
      
        <%= render partial: 'shows/index_grid', :locals => {:shows =>  @artist.shows, :image_only => false, :columns => 3} %>
      
      <%else%>

        <div class="nothing-to-see-container"> 
          <p><%= @artist.name %> does not have any shows listed on ArtYam.</p>
        </div>

      <%end%>

    </div>

  </div>

</div>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @artist.biography %>
</p>

<p>
  <strong>Artist statement:</strong>
  <%= @artist.artist_statement %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @artist.birth_year %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @artist.nationality %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>