config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :artists
  resources :gallery_submissions
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :exhibitions
  resources :charges
  resources :cities
  resources :purchases, only: [:show]
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :item_arts

  root 'pages#home'

  get 'about' => 'pages#about'

  get 'login' => 'pages#login'

  get 'signup' => 'pages#signup'

  get '/settings' => 'pages#settings', as: 'settings'

  get '/how_it_works' => 'pages#how_it_works', as: 'how_it_works'

  get '/affiliates' => 'affiliates#landing_page', as: 'affiliate_landing_page'

  get 'initiate_trial_subscription' => 'subscriptions#initiate_subscription'

  get 'welcome' => 'pages#user_welcome'

  get 'work/new' => 'item_arts#new_work', as: 'new_work'

  get 'balance' => 'pages#balance_payments', as: 'balance_payments'

  get '/dashboard/sales' => 'pages#sales', as: 'sales'

  get 'dashboard/artists' => 'pages#artists', as: 'gallery_artists'

  get 'billing' => 'billing#billing_information', as: 'billing_information'

  get '/:search_code' => 'item_arts#direct_link', as: 'direct_link_to_item_art'

  get '/signup/affiliates' => 'pages#signup_for_affiliates', as: 'signup_for_affiliates'

  get '/signup/galleries' => 'pages#signup_for_galleries', as: 'signup_for_galleries'

  get '/login/affiliates' => 'pages#login_for_affiliates', as: 'login_for_affiliates'

  get '/affiliates/settings' => 'affiliates#settings', as: 'settings_for_affiliates'

  get '/affiliates/payouts' => 'affiliates#payouts', as: 'affiliate_payouts'

  get '/affiliates/dashboard' => 'affiliates#dashboard', as: 'affiliate_dashboard'

  get '/dashboard/messages' => 'pages#messages', as: 'inbox'

  get 'views' => 'pages#views'

  get 'my_purchases' => 'pages#purchases'

  get '/dashboard/settings/accounts' => 'pages#payment_settings', as: 'payment_settings'

  get '/dashboard/settings/payments' => 'pages#customer_payment_settings', as: 'customer_payments'

  get '/dashboard/settings/bank_accounts' => 'pages#bank_accounts', as: 'bank_accounts'

  get 'item_search' => 'item_arts#search'

  post 'setup_user' => "pages#setup_user"

  get 'dashboard/works' => 'pages#my_work', as: 'works'

  get 'dashboard/shows' => 'pages#shows', as: 'dashboard_shows'

  get 'dashboard/engagement' => 'pages#engagement', as: 'engagement'

  post 'update_stripe_account' => 'pages#update_stripe_account'

  post 'update_bank_account' => 'pages#update_bank_account'

  post 'new_bank_account' => 'pages#new_bank_account'

  post '/order/start/create_customer' => 'charges#create_customer', as: 'create_customer'

  post '/home_page/question' => 'pages#question', as: 'question'

  get '/setup/gallery' => 'galleries#inital_create', as: 'gallery_inital_create'

  get '/setup/schedule_call' => 'pages#schedule_setup_call', as: 'schedule_setup_call'

  get '/setup/get_started' => 'pages#get_started', as: 'get_started'

  post '/setup/schedule_call/save' => 'pages#save_setup_call', as: 'save_setup_call'

  post '/setup/gallery/create' => 'galleries#create_for_user', as: 'create_gallery_for_user'

  post '/stripe/webhook/artyam' => 'stripe#webhook', as: 'stripe_webhook'

  get 'item_art/mark_as_sold/:itemID' => 'item_arts#mark_as_sold', as: 'mark_as_sold'

  post '/order/update_contact/:order_id/' => 'charges#update_contact_information', as: 'update_contact_for_order'

  post '/billing/initialize' => 'billing#initiate', as: 'billing_initialize'

  post '/payments/new' => 'purchases#new_card', as: 'new_card'

  post '/submission/:submission_id/checkout' => 'purchases#submission_checkout', as: 'submission_checkout'

  get '/checkout/success/:purchase_id' => 'purchases#checkout_success', as: 'checkout_success'

  post 'email/item/:item_art_id' => 'pages#email_to_me', as: 'email_to_me'

  get 'payments/default/new/:card_id' => 'purchases#new_default_card', as: 'new_default_card'
  
  get 'payments/default/delete/:card_id' => 'purchases#delete_card', as: 'delete_card'
  
  get 'accounts/default/new/:card_id' => 'purchases#new_default_account', as: 'new_default_account'
  
  get 'accounts/delete/:card_id' => 'purchases#delete_account', as: 'delete_account'
  
  get 'artwork/new/add_details/:id' => 'item_arts#detail_form', as: 'item_art_detail_form'
  

  get 'artist/:name' => 'artists#profile', as: 'artist_profile'

  get 'artist/:name/about' => 'artists#profile_about', as: 'artist_profile_about'

  get 'artist/:name/shows' => 'artists#profile_shows', as: 'artist_profile_shows'

  get 'gallery/:name' => 'galleries#profile', as: 'gallery_profile'

  get 'gallery/:name/shows' => 'galleries#profile_shows', as: 'gallery_profile_shows'

  get 'gallery/:name/about' => 'galleries#profile_about', as: 'gallery_profile_about'

  get 'show/:name' => 'shows#profile', as: 'show_profile'

  get 'blog/selling-your-art-in-cafes-restaurants-and-more' => 'blog#selling_your_art', as: 'selling_your_art'
  

  get '/:display_name/about' => 'pages#profile_about', as: 'profile_about'

  get '/work/recently_viewed' => 'pages#recently_viewed', as: 'recently_viewed_work'

  post '/order/start' => 'charges#start_checkout', as: 'start_checkout'

  get '/order/:order_id/payment' => 'charges#start_order', as: 'start_order'

  get '/order/:order_id/contact' => 'charges#add_contact_information', as: 'add_contact_information_to_order'

  get '/purchase/:purchase_id/confirmation' => 'purchases#confirmation', as: 'purchase_confirmation'

  get 'order/:order_id/confirm' => 'charges#confirm_order', as: 'confirm_order'

  post 'order/:order_id/confirm/purchase' => 'charges#confirm_purchase', as: 'confirm_purchase'

  post 'submission/:submission_id/collection/create' => 'gallery_submissions#create_collection', as: 'create_collection'

  get 'submission/:submission_id/confirm' => 'gallery_submissions#confirm_submission', as: 'confirm_submission'

  get 'submissions/select_gallery' => 'gallery_submissions#select_gallery', as: 'select_gallery'

  get 'gallery/submission/format/:id/new' => 'galleries#submission_format', as: 'gallery_submission_format'

  get 'gallery/submission/format/save' => 'galleries#submission_format_save', as: 'gallery_submission_formats'
  
  get 'gallery/submission/setup/:gallery_id' => 'gallery_submissions#setup', as: 'gallery_submission_setup'

end

app/views/modals/_checkout_modal.html.erb
<div class="modal-container" id="checkout-modal">

	<div class="modal-content">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

		<%= form_tag submission_checkout_path, id: 'chargeForm' do %>

			<h3><b>Payment Method</b></h3>

			<label>Card number</label>

			<div class="input-container">

				<input type="text" name="cardNumber" id="cardNumberInput" class="cc-form card-number" maxlength="18" required></input>

			</div>


			<div class="input-group">

				<label>Expiration Date</label>

				<br>

				<ul class="horizontal">

					<li><select class="cc-select" name='expMonth' id='expireMM' required>
				    <option value=''>Month</option>
				    <option value='01'>01</option>
				    <option value='02'>02</option>
				    <option value='03'>03</option>
				    <option value='04'>04</option>
				    <option value='05'>05</option>
				    <option value='06'>06</option>
				    <option value='07'>07</option>
				    <option value='08'>08</option>
				    <option value='09'>09</option>
				    <option value='10'>10</option>
				    <option value='11'>11</option>
				    <option value='12'>12</option>
					</select></li>
					<li><select class="cc-select" name='expYear' id='expireYY' required>
				    <option value=''>Year</option>
				    <option value='16'>2016</option>
				    <option value='17'>2017</option>
				    <option value='18'>2018</option>
				    <option value='19'>2019</option>
				    <option value='20'>2020</option>
				    <option value='21'>2021</option>
				    <option value='22'>2022</option>
					</select></li>

				</ul>

			</div>

			<div class="input-group">
				<label>Security Code</label>
				<br>
				<input type="text" name="cvc" class="cc-form card-cvc" maxlength="4" required></input>
			</div>

			<br>

			<div class="input-container">

				<label>Name on card</label>

				<input type="text" name="nameOnCard" class="cc-form card-name" required></input>

			</div>

			<br>

			<input type="submit" class="button stretch blue-background" value="Pay <%= number_to_currency(total_cost) %>">

		<% end %>

	</div>

</div>

app/views/modals/_create_account.html.erb
<div class="modal-container brand-gradient-background vertical" id="create-account-modal">

	<div class="modal-content centered">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

		<div class="simple-landing-container">

			<%= form_for(:user, :url => registration_path(:user)) do |f| %>

			    <h2 class="light">Sign up</h2>

			    <% if @purchase%>
			    	<%= hidden_field_tag 'purchase_id', @purchase.id %>
			    <%end%>

			    <div class="field">
			      <%= f.email_field :email, autofocus: true, placeholder: "Email" %>
			    </div>
			    
			    <div class="field">
			      <%= f.text_field :display_name, placeholder: "Display Name" %>
			    </div>

			    <div class="field">
			      <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
			    </div>

			    <div class="actions">
			      <%= f.submit "Create Account", class: "button medium orange-background" %>
			    </div>

			<% end %>

		</div>

	</div>

</div>

app/views/modals/_email_to_me.html.erb
<div class="modal-container brand-gradient-background vertical mobile-device-only" id="email-to-me-modal">

	<div class="modal-content centered">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

		<div class="simple-landing-container">

			<%= form_tag email_to_me_path(item.id), id: 'emailMeForm' do %>

				<input type="text" name="email" class="" required></input>

				<br>

				<input type="submit" class="button large orange-background" value="Send Email">
			   
			<% end %>

		</div>

	</div>

</div>

app/views/modals/_home_search.html.erb
<div class="modal-container brand-gradient-background vertical mobile-device-only">

	<div class="modal-content centered">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

		<form class="home-search-form" action="/item_search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">

			<ul class="horizontal header-search-form">

				<li><input type="text" class="transparent large-input centered search-code-input" name="search" id="search" placeholder="Search Code" autofocus></li><!-- <li><button type="submit" class="red-background search-code-input"><span class="glyphicon glyphicon-search"></span></button></li> -->

			</ul>

			<br><br>

			<input type="submit" class="orange-background large button" value="Find">
		    
		   
		</form>

	</div>

</div>

app/views/modals/_new_account_modal.html.erb
<div class="modal-container" id="new-account-modal">

	<div class="modal-content">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

			<h3>Bank Account Details</h3>

		  	<%= form_tag new_bank_account_path, id: 'bankAccountForm', class: 'edit_user_settings' do %>

			<div class="field">

				<p><b>Bank Location</b></p>

				<select name="country" required>
		            <option value="US">United States</option>
		           	<option value="CAN">Canada</option>
		        </select>

			</div>

			<br>

			<div class="field">

				<p><b>Name on Account</b></p>

				<input type="text" name="accountHolder" required/>

			</div>

			<br>

			<div class="field">

				<p><b>Routing Number</b></p>

				<input type="text" size="9" name="routingNumber" autocomplete="off" required>

			</div>

			<br>

			<div class="field">

				<p><b>Account Number</b></p>

				<input type="text" size="17" name="accountNumber" autocomplete="off" required>

			</div>

			<br>

			<input type="submit" value="<% if @defaultaccount %>Update Bank Account<%else%>Add Bank Account<%end%>" class= "orange-background medium">

  		<% end %>

	</div>

</div>

app/views/modals/_new_artwork_image.html.erb
<div class="modal-content full-screen centered" id="new-artwork-image-modal" style="display: none;">

	<span class="glyphicon glyphicon-remove dismiss-modal dismiss-parent"></span>

	  <%= form_for(item_art) do |f| %>

	    <% if item_art.errors.any? %>
	      <div id="error_explanation">
	        <h2><%= pluralize(item_art.errors.count, "error") %> prohibited this item_art from being saved:</h2>

	        <ul>
	        <% item_art.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	        </ul>
	      </div>
	    <% end %>

	    <div class="image-input-container">
	      
	      <span id="image-input-header-upload" class="glyphicon glyphicon-upload" aria-hidden="true"></span><h2 id="image-input-header-check" style="display: none; "><span class="glyphicon glyphicon-ok" aria-hidden="true" style="margin-right: 5px; color: #31A231;"></span>Image Successfully Uploaded.</h2>

	      <h2 id="image-input-header-text">Click to Upload a Photo of Your Artwork</h2>
	      
	      <%= f.file_field :image, required: true, class: "form-control full-screen artwork-image-input" %>

	    </div>

<!-- 		        <img id="image_upload_preview" src="http://placehold.it/100x100" alt="your image" /> -->

	        <br>

	      <%= f.submit "Save & Continue", class: "button large bright-blue-background artwork-image-submit default-off" %>
	        

	  <% end %>

</div>

app/views/modals/_new_card_modal.html.erb
<div class="modal-container" id="new-card-modal">

	<div class="modal-content">

		<span class="glyphicon glyphicon-remove dismiss-modal"></span>

		<%= form_tag new_card_path, id: 'chargeForm' do %>

			<h3><b>New Payment Method</b></h3>

			<label>Card number</label>

			<div class="input-container">

				<input type="text" name="cardNumber" id="cardNumberInput" class="cc-form card-number" maxlength="18" required></input>

			</div>


			<div class="input-group">

				<label>Expiration Date</label>

				<br>

				<ul class="horizontal">

					<li><select class="cc-select" name='expMonth' id='expireMM' required>
				    <option value=''>Month</option>
				    <option value='01'>01</option>
				    <option value='02'>02</option>
				    <option value='03'>03</option>
				    <option value='04'>04</option>
				    <option value='05'>05</option>
				    <option value='06'>06</option>
				    <option value='07'>07</option>
				    <option value='08'>08</option>
				    <option value='09'>09</option>
				    <option value='10'>10</option>
				    <option value='11'>11</option>
				    <option value='12'>12</option>
					</select></li>
					<li><select class="cc-select" name='expYear' id='expireYY' required>
				    <option value=''>Year</option>
				    <option value='16'>2016</option>
				    <option value='17'>2017</option>
				    <option value='18'>2018</option>
				    <option value='19'>2019</option>
				    <option value='20'>2020</option>
				    <option value='21'>2021</option>
				    <option value='22'>2022</option>
					</select></li>

				</ul>

			</div>

			<div class="input-group">
				<label>Security Code</label>
				<br>
				<input type="text" name="cvc" class="cc-form card-cvc" maxlength="4" required></input>
			</div>

			<br>

			<div class="input-container">

				<label>Name on card</label>

				<input type="text" name="nameOnCard" class="cc-form card-name" required></input>

			</div>

			<br>

			<input type="submit" class="button stretch blue-background" value="Save Credit Card">

		<% end %>

	</div>

</div>