config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :artists
  resources :gallery_submissions
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :exhibitions
  resources :charges
  resources :cities
  resources :purchases, only: [:show]
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :item_arts

  root 'pages#home'

  get 'about' => 'pages#about'

  get 'login' => 'pages#login'

  get 'signup' => 'pages#signup'

  get '/settings' => 'pages#settings', as: 'settings'

  get '/how_it_works' => 'pages#how_it_works', as: 'how_it_works'

  get '/affiliates' => 'affiliates#landing_page', as: 'affiliate_landing_page'

  get 'initiate_trial_subscription' => 'subscriptions#initiate_subscription'

  get 'welcome' => 'pages#user_welcome'

  get 'work/new' => 'item_arts#new_work', as: 'new_work'

  get 'balance' => 'pages#balance_payments', as: 'balance_payments'

  get '/dashboard/sales' => 'pages#sales', as: 'sales'

  get 'dashboard/artists' => 'pages#artists', as: 'gallery_artists'

  get 'billing' => 'billing#billing_information', as: 'billing_information'

  get '/:search_code' => 'item_arts#direct_link', as: 'direct_link_to_item_art'

  get '/signup/affiliates' => 'pages#signup_for_affiliates', as: 'signup_for_affiliates'

  get '/signup/galleries' => 'pages#signup_for_galleries', as: 'signup_for_galleries'

  get '/login/affiliates' => 'pages#login_for_affiliates', as: 'login_for_affiliates'

  get '/affiliates/settings' => 'affiliates#settings', as: 'settings_for_affiliates'

  get '/affiliates/payouts' => 'affiliates#payouts', as: 'affiliate_payouts'

  get '/affiliates/dashboard' => 'affiliates#dashboard', as: 'affiliate_dashboard'

  get '/dashboard/messages' => 'pages#messages', as: 'inbox'

  get 'views' => 'pages#views'

  get 'my_purchases' => 'pages#purchases'

  get '/dashboard/settings/accounts' => 'pages#payment_settings', as: 'payment_settings'

  get '/dashboard/settings/payments' => 'pages#customer_payment_settings', as: 'customer_payments'

  get '/dashboard/settings/bank_accounts' => 'pages#bank_accounts', as: 'bank_accounts'

  get 'item_search' => 'item_arts#search'

  post 'setup_user' => "pages#setup_user"

  get 'dashboard/works' => 'pages#my_work', as: 'works'

  get 'dashboard/shows' => 'pages#shows', as: 'dashboard_shows'

  get 'dashboard/engagement' => 'pages#engagement', as: 'engagement'

  post 'update_stripe_account' => 'pages#update_stripe_account'

  post 'update_bank_account' => 'pages#update_bank_account'

  post 'new_bank_account' => 'pages#new_bank_account'

  post '/order/start/create_customer' => 'charges#create_customer', as: 'create_customer'

  post '/home_page/question' => 'pages#question', as: 'question'

  get '/setup/gallery' => 'galleries#inital_create', as: 'gallery_inital_create'

  get '/setup/schedule_call' => 'pages#schedule_setup_call', as: 'schedule_setup_call'

  get '/setup/get_started' => 'pages#get_started', as: 'get_started'

  post '/setup/schedule_call/save' => 'pages#save_setup_call', as: 'save_setup_call'

  post '/setup/gallery/create' => 'galleries#create_for_user', as: 'create_gallery_for_user'

  post '/stripe/webhook/artyam' => 'stripe#webhook', as: 'stripe_webhook'

  get 'item_art/mark_as_sold/:itemID' => 'item_arts#mark_as_sold', as: 'mark_as_sold'

  post '/order/update_contact/:order_id/' => 'charges#update_contact_information', as: 'update_contact_for_order'

  post '/billing/initialize' => 'billing#initiate', as: 'billing_initialize'

  post '/payments/new' => 'purchases#new_card', as: 'new_card'

  post '/submission/:submission_id/checkout' => 'purchases#submission_checkout', as: 'submission_checkout'

  get '/checkout/success/:purchase_id' => 'purchases#checkout_success', as: 'checkout_success'

  post 'email/item/:item_art_id' => 'pages#email_to_me', as: 'email_to_me'

  get 'payments/default/new/:card_id' => 'purchases#new_default_card', as: 'new_default_card'
  
  get 'payments/default/delete/:card_id' => 'purchases#delete_card', as: 'delete_card'
  
  get 'accounts/default/new/:card_id' => 'purchases#new_default_account', as: 'new_default_account'
  
  get 'accounts/delete/:card_id' => 'purchases#delete_account', as: 'delete_account'
  
  get 'artwork/new/add_details/:id' => 'item_arts#detail_form', as: 'item_art_detail_form'
  

  get 'artist/:name' => 'artists#profile', as: 'artist_profile'

  get 'artist/:name/about' => 'artists#profile_about', as: 'artist_profile_about'

  get 'artist/:name/shows' => 'artists#profile_shows', as: 'artist_profile_shows'

  get 'gallery/:name' => 'galleries#profile', as: 'gallery_profile'

  get 'gallery/:name/shows' => 'galleries#profile_shows', as: 'gallery_profile_shows'

  get 'gallery/:name/about' => 'galleries#profile_about', as: 'gallery_profile_about'

  get 'show/:name' => 'shows#profile', as: 'show_profile'

  get 'blog/selling-your-art-in-cafes-restaurants-and-more' => 'blog#selling_your_art', as: 'selling_your_art'
  

  get '/:display_name/about' => 'pages#profile_about', as: 'profile_about'

  get '/work/recently_viewed' => 'pages#recently_viewed', as: 'recently_viewed_work'

  post '/order/start' => 'charges#start_checkout', as: 'start_checkout'

  get '/order/:order_id/payment' => 'charges#start_order', as: 'start_order'

  get '/order/:order_id/contact' => 'charges#add_contact_information', as: 'add_contact_information_to_order'

  get '/purchase/:purchase_id/confirmation' => 'purchases#confirmation', as: 'purchase_confirmation'

  get 'order/:order_id/confirm' => 'charges#confirm_order', as: 'confirm_order'

  post 'order/:order_id/confirm/purchase' => 'charges#confirm_purchase', as: 'confirm_purchase'

  post 'submission/:submission_id/collection/create' => 'gallery_submissions#create_collection', as: 'create_collection'

  get 'submission/:submission_id/confirm' => 'gallery_submissions#confirm_submission', as: 'confirm_submission'

  get 'submissions/select_gallery' => 'gallery_submissions#select_gallery', as: 'select_gallery'

  get 'gallery/submission/format/:id/new' => 'galleries#submission_format', as: 'gallery_submission_format'

  get 'gallery/submission/format/save' => 'galleries#submission_format_save', as: 'gallery_submission_formats'
  
  get 'gallery/submission/setup/:gallery_id' => 'gallery_submissions#setup', as: 'gallery_submission_setup'

end

app/models/gallery_submission.rb
class GallerySubmission < ActiveRecord::Base

	has_one :collection

	belongs_to :gallery

	belongs_to :user

	def status

		unless self.paid

			return "Draft"

		else

			return "Sent to Gallery"

		end
		
	end

end

app/controllers/gallery_submissions_controller.rb
class GallerySubmissionsController < InheritedResources::Base

	def setup

		@return_home_only = true

		@step_title = "select_artwork"

		@page_title = "Gallery Submission"

		if user_signed_in?

			if Gallery.where(:id => params[:gallery_id]).exists?

				@gallery = Gallery.find(params[:gallery_id])

				unless GallerySubmission.where(:user_id => current_user.id, :gallery_id => @gallery.id).exists?

					@gallery_submission = GallerySubmission.new

					@gallery_submission.update(:gallery_id => @gallery.id, :user_id => current_user.id)


				else

					@gallery_submission = GallerySubmission.where(:user_id => current_user.id, :gallery_id => @gallery.id).last
					#redirect_to root_path


				end

				
			else
				
				redirect_to root_path

			end

		else

			redirect_to root_path

		end

	end


	def create_collection

		@return_home_only = true

		@page_title = "Gallery Submission"

		@step_title = "select_artwork"

		@gallery_submission = GallerySubmission.find(params[:submission_id])

		@gallery = @gallery_submission.gallery

		if user_signed_in?
			
			unless Collection.where(:user_id => current_user.id, :gallery_submission_id => params[:submission_id]).exists?

				@collection = Collection.new

				@collection.update(:user_id => current_user.id, :gallery_submission_id => params[:submission_id])

				@collection.save

			else

				@collection = Collection.where(:user_id => current_user.id, :gallery_submission_id => params[:submission_id]).last

				CollectionItem.where(:gallery_submission_id => @collection.gallery_submission_id).destroy_all


			end

			params[:item].each do |item|

				if item[1] == "on"

					collection_item = CollectionItem.new
					collection_item.update(:user_id => current_user.id, :item_art_id => item[0], :gallery_submission_id => params[:submission_id], :collection_id => @collection.id)
					collection_item.save

				end

			end

			redirect_to confirm_submission_path(@gallery_submission.id)

		else

			redirect_to root_path

		end
		
	end

	def select_gallery

		@return_home_only = true

		@page_title = "Gallery Submission"

		@step_title = "select_gallery"


	end

	def confirm_submission

		if user_signed_in?

			@return_home_only = true

			@page_title = "Gallery Submission"

			@step_title = "confirm_pay"

			@gallery_submission = GallerySubmission.find(params[:submission_id])

			@gallery = @gallery_submission.gallery

			@collection = Collection.where(:user_id => current_user.id, :gallery_submission_id => params[:submission_id]).last

			unless @collection

				redirect_to root_path

			end

		else

			redirect_to root_path

		end

	end



  private

    def gallery_submission_params
      params.require(:gallery_submission).permit(:user_id, :gallery_id, :collection_id, :additional_description)
    end
end

app/helpers/gallery_submissions_helper.rb
module GallerySubmissionsHelper
end

app/views/gallery_submissions/_form.html.erb
<%= form_for(@gallery_submission) do |f| %>
  <% if @gallery_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_submission.errors.count, "error") %> prohibited this gallery_submission from being saved:</h2>

      <ul>
      <% @gallery_submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :gallery_id %><br>
    <%= f.number_field :gallery_id %>
  </div>
  <div class="field">
    <%= f.label :collection_id %><br>
    <%= f.number_field :collection_id %>
  </div>
  <div class="field">
    <%= f.label :additional_description %><br>
    <%= f.text_area :additional_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_submissions/_gallery_submission_step_header.html.erb
<div class="phase-header">

  <ul class="horizontal">
    <li><span class="circular-number list">1</span><span class="<% if @step_title =="select_gallery"%>active<%end%> step">Select Gallery</span></li>
    <li><span class="circular-number list">2</span><span class="<% if @step_title =="select_artwork"%>active<%end%> step">Choose Artwork</span></li>
    <li><span class="circular-number list">3</span><span class="<% if @step_title =="confirm_pay"%>active<%end%> step">Confirm & Pay</span></li>

  </ul>

</div>

app/views/gallery_submissions/confirm_submission.html.erb
<%= render 'gallery_submissions/gallery_submission_step_header' %>

<div class="content">

  <ul class="horizontal centered step-header">
    
    <li><span class="glyphicon glyphicon glyphicon-ok circular-number"></span><a class="step" href="<%= select_gallery_path %>">Select Gallery</a></li>
    <li><span class="glyphicon glyphicon glyphicon-ok circular-number"></span><a class="step" href="<%= gallery_submission_setup_path(@gallery.id) %>" >Choose Artwork</a></li>
    <li><span class="circular-number">3</span><br><span class="active step">Confirm & Pay</a></li>

  </ul>

    <div class="button-container">
      <input type="submit" class="button large green-background modal-cta checkout-modal-cta" value="Submit Portfolio for $9"/>
    </div>


    <h4 class="centered">Your Portfolio Submission to <span style="color: blue;"><%= @gallery_submission.gallery.name %></span>:</h4>

    <br>

    <table class="select-item-table">

        <thead>

          <tr>
            <th></th>
            <th>Title</th>
            <th>Medium</th>
            <th>Price</th>
          </tr>

        </thead>

        <tbody>

          <% @collection.items.each do |item| %>

            <tr class="outlined">

              <td><%= image_tag item.image.url, class: "small-image"%></td>
              <td><%= item.name %></td>
              <td><%= item.medium %></td>
              <td><%= number_to_currency(item.price, precision: 0) %></td>
              
            </tr>

          <%end%>

        </tbody>

    </table>

    <div class="button-container">
      <input type="submit" class="button large green-background" value="Submit Portfolio for $9"/>
    </div>

  <%#end%>

</div>

<%= render :partial => 'modals/checkout_modal', :locals => {:total_cost => 9} %>

app/views/gallery_submissions/create_collection.html.erb
<%= render 'gallery_submissions/gallery_submission_step_header' %>

<div class="content">

  <h2 class="centered instructions">Confirm Portfolio Submission to <span style="color: blue;"><%= @gallery.name %></span></h2>
  
  <%# form_tag create_collection_path(@gallery_submission.id) do %>
  <%# form_for(@gallery_submission) do |f| %>

    <input type="submit" value="Save"/>

    <table class="select-item-table">

        <thead>

          <tr>
            <th></th>
            <th>Title</th>
            <th>Medium</th>
            <th>Price</th>
          </tr>

        </thead>

        <tbody>

          <% @collection.items.each do |item| %>

            <tr class="outlined">

              <td><%= image_tag item.image.url, class: "small-image"%></td>
              <td><%= item.name %></td>
              <td><%= item.medium %></td>
              <td><%= number_to_currency(item.price, precision: 0) %></td>
              
            </tr>

          <%end%>

        </tbody>

    </table>

  <%#end%>

</div>

app/views/gallery_submissions/edit.html.erb
<h1>Editing Gallery Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_submission %> |
<%= link_to 'Back', gallery_submissions_path %>

app/views/gallery_submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gallery Submissions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gallery</th>
      <th>Collection</th>
      <th>Additional description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_submissions.each do |gallery_submission| %>
      <tr>
        <td><%= gallery_submission.user_id %></td>
        <td><%= gallery_submission.gallery_id %></td>
        <td><%= gallery_submission.collection_id %></td>
        <td><%= gallery_submission.additional_description %></td>
        <td><%= link_to 'Show', gallery_submission %></td>
        <td><%= link_to 'Edit', edit_gallery_submission_path(gallery_submission) %></td>
        <td><%= link_to 'Destroy', gallery_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery submission', new_gallery_submission_path %>

app/views/gallery_submissions/new.html.erb
<h1>New Gallery Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_submissions_path %>

app/views/gallery_submissions/select_gallery.html.erb
<%= render 'gallery_submissions/gallery_submission_step_header' %>

<div class="content">
	
	<div class="portfolio-container">

		<%# if current_user.item_arts.count > 0 %>
			
			<div class="image-grid">

				<% current_user.galleries_for_submission.all.each do |gallery| %>

					<%= link_to(gallery_submission_setup_path(gallery.id)) do %>

						<div class="entry">

							<div class="outline">
							
								<div class="image-container">
									<%# image_tag gallery.image.url, class: "grid-image"%>
								</div>

								<div class="detail-container">

									<h4><%= gallery.name %></h4>

								    <h4><span>Select</span></h4>

							    </div>

							</div>

						</div>

					<% end %>

				<% end %>

			</div>

		<%#else%>

<!-- 			<div class="nothing-to-see-container">

				<p class="red">You have not shared any artwork yet. <%# link_to "Add Artwork", new_item_art_path, class: "warning-text-cta" %></p>

			</div> -->

		<%#end%>

	</div>

</div>

app/views/gallery_submissions/setup.html.erb
<%= render 'gallery_submissions/gallery_submission_step_header' %>

<div class="content">

  <%= form_tag create_collection_path(@gallery_submission.id) do %>

  <h4 class="centered">Choose Up to <%= @gallery_submission.gallery.number_of_images %> Pieces to Submit to <span style="color: blue;"><%= @gallery_submission.gallery.name %></span>:</h4>

  <br>

    <table class="select-item-table">

        <thead>

          <tr>
            <th></th>
            <th>Title</th>
            <th>Medium</th>
            <th>Price</th>
          </tr>

        </thead>

        <tbody>
        
          <% current_user.item_arts.all.each do |item| %>

            <tr class="outlined clickable green-on-click">

              <td><%= image_tag item.image.url, class: "small-image"%></td>
              <td><%= item.name %></td>
              <td><%= item.medium %></td>
              <td><%= number_to_currency(item.price, precision: 0) %></td>
              <td class="default-off"><input class="select-item-checkbox" name="item[<%=item.id%>]" type="checkbox"/></td>

            </tr>

          <%end%>

        </tbody>

    </table>


    <div class="button-container">
      <input type="submit" class="button large bright-blue-background" value="Next"/>
    </div>

  <%end%>

</div>

app/views/gallery_submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @gallery_submission.user_id %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @gallery_submission.gallery_id %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @gallery_submission.collection_id %>
</p>

<p>
  <strong>Additional description:</strong>
  <%= @gallery_submission.additional_description %>
</p>

<%= link_to 'Edit', edit_gallery_submission_path(@gallery_submission) %> |
<%= link_to 'Back', gallery_submissions_path %>