config/routes.rb
Rails.application.routes.draw do
  resources :shows
  resources :artists
  resources :gallery_submissions
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages
  resources :exhibitions
  resources :charges
  resources :cities
  resources :purchases, only: [:show]
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :item_arts

  root 'pages#home'

  get 'about' => 'pages#about'

  get 'login' => 'pages#login'

  get 'signup' => 'pages#signup'

  get '/settings' => 'pages#settings', as: 'settings'

  get '/how_it_works' => 'pages#how_it_works', as: 'how_it_works'

  get '/affiliates' => 'affiliates#landing_page', as: 'affiliate_landing_page'

  get 'initiate_trial_subscription' => 'subscriptions#initiate_subscription'

  get 'welcome' => 'pages#user_welcome'

  get 'work/new' => 'item_arts#new_work', as: 'new_work'

  get 'balance' => 'pages#balance_payments', as: 'balance_payments'

  get '/dashboard/sales' => 'pages#sales', as: 'sales'

  get 'dashboard/artists' => 'pages#artists', as: 'gallery_artists'

  get 'billing' => 'billing#billing_information', as: 'billing_information'

  get '/:search_code' => 'item_arts#direct_link', as: 'direct_link_to_item_art'

  get '/signup/affiliates' => 'pages#signup_for_affiliates', as: 'signup_for_affiliates'

  get '/signup/galleries' => 'pages#signup_for_galleries', as: 'signup_for_galleries'

  get '/login/affiliates' => 'pages#login_for_affiliates', as: 'login_for_affiliates'

  get '/affiliates/settings' => 'affiliates#settings', as: 'settings_for_affiliates'

  get '/affiliates/payouts' => 'affiliates#payouts', as: 'affiliate_payouts'

  get '/affiliates/dashboard' => 'affiliates#dashboard', as: 'affiliate_dashboard'

  get '/dashboard/messages' => 'pages#messages', as: 'inbox'

  get 'views' => 'pages#views'

  get 'my_purchases' => 'pages#purchases'

  get '/dashboard/settings/accounts' => 'pages#payment_settings', as: 'payment_settings'

  get '/dashboard/settings/payments' => 'pages#customer_payment_settings', as: 'customer_payments'

  get '/dashboard/settings/bank_accounts' => 'pages#bank_accounts', as: 'bank_accounts'

  get 'item_search' => 'item_arts#search'

  post 'setup_user' => "pages#setup_user"

  get 'dashboard/works' => 'pages#my_work', as: 'works'

  get 'dashboard/shows' => 'pages#shows', as: 'dashboard_shows'

  get 'dashboard/engagement' => 'pages#engagement', as: 'engagement'

  post 'update_stripe_account' => 'pages#update_stripe_account'

  post 'update_bank_account' => 'pages#update_bank_account'

  post 'new_bank_account' => 'pages#new_bank_account'

  post '/order/start/create_customer' => 'charges#create_customer', as: 'create_customer'

  post '/home_page/question' => 'pages#question', as: 'question'

  get '/setup/gallery' => 'galleries#inital_create', as: 'gallery_inital_create'

  get '/setup/schedule_call' => 'pages#schedule_setup_call', as: 'schedule_setup_call'

  get '/setup/get_started' => 'pages#get_started', as: 'get_started'

  post '/setup/schedule_call/save' => 'pages#save_setup_call', as: 'save_setup_call'

  post '/setup/gallery/create' => 'galleries#create_for_user', as: 'create_gallery_for_user'

  post '/stripe/webhook/artyam' => 'stripe#webhook', as: 'stripe_webhook'

  get 'item_art/mark_as_sold/:itemID' => 'item_arts#mark_as_sold', as: 'mark_as_sold'

  post '/order/update_contact/:order_id/' => 'charges#update_contact_information', as: 'update_contact_for_order'

  post '/billing/initialize' => 'billing#initiate', as: 'billing_initialize'

  post '/payments/new' => 'purchases#new_card', as: 'new_card'

  post '/submission/:submission_id/checkout' => 'purchases#submission_checkout', as: 'submission_checkout'

  get '/checkout/success/:purchase_id' => 'purchases#checkout_success', as: 'checkout_success'

  post 'email/item/:item_art_id' => 'pages#email_to_me', as: 'email_to_me'

  get 'payments/default/new/:card_id' => 'purchases#new_default_card', as: 'new_default_card'
  
  get 'payments/default/delete/:card_id' => 'purchases#delete_card', as: 'delete_card'
  
  get 'accounts/default/new/:card_id' => 'purchases#new_default_account', as: 'new_default_account'
  
  get 'accounts/delete/:card_id' => 'purchases#delete_account', as: 'delete_account'
  
  get 'artwork/new/add_details/:id' => 'item_arts#detail_form', as: 'item_art_detail_form'
  

  get 'artist/:name' => 'artists#profile', as: 'artist_profile'

  get 'artist/:name/about' => 'artists#profile_about', as: 'artist_profile_about'

  get 'artist/:name/shows' => 'artists#profile_shows', as: 'artist_profile_shows'

  get 'gallery/:name' => 'galleries#profile', as: 'gallery_profile'

  get 'gallery/:name/shows' => 'galleries#profile_shows', as: 'gallery_profile_shows'

  get 'gallery/:name/about' => 'galleries#profile_about', as: 'gallery_profile_about'

  get 'show/:name' => 'shows#profile', as: 'show_profile'

  get 'blog/selling-your-art-in-cafes-restaurants-and-more' => 'blog#selling_your_art', as: 'selling_your_art'
  

  get '/:display_name/about' => 'pages#profile_about', as: 'profile_about'

  get '/work/recently_viewed' => 'pages#recently_viewed', as: 'recently_viewed_work'

  post '/order/start' => 'charges#start_checkout', as: 'start_checkout'

  get '/order/:order_id/payment' => 'charges#start_order', as: 'start_order'

  get '/order/:order_id/contact' => 'charges#add_contact_information', as: 'add_contact_information_to_order'

  get '/purchase/:purchase_id/confirmation' => 'purchases#confirmation', as: 'purchase_confirmation'

  get 'order/:order_id/confirm' => 'charges#confirm_order', as: 'confirm_order'

  post 'order/:order_id/confirm/purchase' => 'charges#confirm_purchase', as: 'confirm_purchase'

  post 'submission/:submission_id/collection/create' => 'gallery_submissions#create_collection', as: 'create_collection'

  get 'submission/:submission_id/confirm' => 'gallery_submissions#confirm_submission', as: 'confirm_submission'

  get 'submissions/select_gallery' => 'gallery_submissions#select_gallery', as: 'select_gallery'

  get 'gallery/submission/format/:id/new' => 'galleries#submission_format', as: 'gallery_submission_format'

  get 'gallery/submission/format/save' => 'galleries#submission_format_save', as: 'gallery_submission_formats'
  
  get 'gallery/submission/setup/:gallery_id' => 'gallery_submissions#setup', as: 'gallery_submission_setup'

end

app/models/show.rb
class Show < ActiveRecord::Base

	belongs_to :gallery

	has_many :item_arts

	belongs_to :artist

	has_attached_file :image, 
	:styles => { :medium => "100x100#", :small => "70x70#", :thumb => "30x30#"},
	:default_url => 'missing_item_photo.png',
	:s3_protocol => :https


	def other_work_in_this_show(item, count)

    return self.item_arts.where.not(id: item).last(count)

  end


end

app/controllers/shows_controller.rb
class ShowsController < InheritedResources::Base



	def new

		@form_header_prompt = "Enter Show Details"


		@show = Show.new

		@page_title = "New Work"

		@return_home_only = true


	end

	def profile

		@show = Show.where(:name => params[:name]).last

		@page_title = @show.name
		
	end



	def create
    
	    if user_signed_in?

	      @show = Show.new(show_params)


	      if params[:begin_date]

	      	@show.update(:begin_date => params[:begin_date])

	      end



	      if params[:end_date]

	      	@show.update(:end_date => params[:end_date])

	      end

	      respond_to do |format|
	        if @show.save
	          format.html { redirect_to dashboard_shows_path, notice: 'Show successfully created.' }
	          format.json { render :show, status: :created, location: @show }
	        else
	          format.html { render :new }
	          format.json { render json: @show.errors, status: :unprocessable_entity }
	        end
	      end

	    else

	      redirect_to root_path
	    end
  end





  private

    def show_params
      params.require(:show).permit(:is_festival, :name, :begin_date, :end_date, :open_to_public, :gallery_id, :artist_id)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%# f.label :is_festival %><br>
    <%# f.check_box :is_festival %>
  </div> -->

  <div class="field">
    <label>Name of Show</label><br>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field">

    <label>Image</label>

    <br>

    <div style="position:relative; display: inline-block;">
      <%= image_tag @show.image.url, class: "item-art-medium-image" %>
      <%= f.file_field :image, class: "form-control clickable fill-container clear" %>
    </div>

  </div>

  <% if current_user.galleries.count > 1 %>
    
    <div class="field">
      <label>Gallery/Venue</label><br>
      <%= f.collection_select :gallery_id, current_user.galleries, :id, :name, :prompt => true %>
    </div>


  <% elsif current_user.galleries.count == 1 %>

    <%= f.hidden_field :gallery_id, :value => current_user.galleries.last.id %>

  <%end%>

  <div class="field">

      <label>Artist</label><br>
      <%= f.collection_select :artist_id, current_user.my_artists, :id, :name, :prompt => true %>
  
  </div>


  <div class="field">

    <table class="input-table">

      <tr>
        <td style="padding-right: 20px;"><label>Start Date</label></td>
        <td><label>End Date</label></td>
      </tr>

      <tr>
        <td style="padding-right: 20px;"><input type="text" class="datepicker" name="begin_date" required></td>
        <td><input type="text" class="datepicker" name="end_date" required></td>
      </tr>

    </table>

  </div>

  <div class="field">
    <label>Open to the Public?</label><br>
    <%= f.check_box :open_to_public %>
  </div>
<!--   <div class="field">
    <%# f.label :gallery_id %><br>
    <%# f.number_field :gallery_id %>
  </div> -->
  <div class="actions">
    <%= f.submit "Save Details", class: "button large black-background" %>
  </div>
<% end %>

app/views/shows/_index_grid.html.erb
<% if shows.count > 0 %>

<div class="image-grid">

	<% shows.each do |show| %>

		<div class="entry <% if image_only %>image-only<%end%><% if columns == 2 %>col-2<%end%>">
			
			<% if user_signed_in? %>

				<%= link_to(show_profile_path(show.name)) do %>

					<div class="image-container">

						<%= image_tag show.image.url, class: "grid-image"%>

					</div>

				<% end %>


			<%else%>

				<%= link_to(show_profile_path(show.name)) do %>

					<div class="image-container">

						<%= image_tag show.image.url, class: "grid-image"%>

					</div>

				<% end %>

			<%end%>
			
				
			<% unless image_only %>

				<div class="detail-container">

					<a class="artwork-metadata artist-name"><%= show.name %></a>
					<br>


					<a class="artwork-metadata"> <%= show.begin_date.strftime("%b %e") %> - <%= show.end_date.strftime("%b %e") %></a>
					<br>

		    	</div>

	    	<%end%>

		</div>

	<% end %>

</div>

<%else%>

	<div class="nothing-to-see-container"> 
          <p>No shows listed on ArtYam yet.</p>
    </div>

<%end%>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shows</h1>

<table>
  <thead>
    <tr>
      <th>Is festival</th>
      <th>Name</th>
      <th>Begin date</th>
      <th>End date</th>
      <th>Open to public</th>
      <th>Gallery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.is_festival %></td>
        <td><%= show.name %></td>
        <td><%= show.begin_date %></td>
        <td><%= show.end_date %></td>
        <td><%= show.open_to_public %></td>
        <td><%= show.gallery_id %></td>
        <td><%= link_to 'Show', show %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<div class="content">

	<div class="form-container">

		<h4><%= @form_header_prompt %></h4>

		<%= render 'form' %>

	</div>

</div>

app/views/shows/profile.html.erb
<div class="open-page-container">

  <div class="profile-header">

    <div class="profile-header-content">

        <%= image_tag @show.image.url(:medium), class: "medium-profile-image"%>

        <br>

        <h2><%= @show.name %></h2>

        <h4><%= link_to @show.gallery.name, gallery_profile_path(@show.gallery.name) %></h4>

        <p><%= @show.gallery.city %>, <%= @show.gallery.state_province %></p>

        <p><%= @show.begin_date.strftime("%b %e") %> - <%= @show.end_date.strftime("%b %e") %></p>

        <br>

        <h4>Artist: <%= link_to @show.artist.name, artist_profile_path(@show.artist.name) %></h4>
        <p><%= @show.item_arts.count %> Pieces</p>

        <br>
        
        <p><%= @show.about %></p>

    </div>

  </div>

  <div class="profile-content">

    <div class="section-header-nav">



    </div>


      <div id="works">

        <% if @show.item_arts.count > 0 %>

          <%= render :partial => 'item_arts/index_grid', :locals => {:items => @show.item_arts.reverse, :image_only => false, :columns => 3} %>

        <%else%>

        <%end%>

      </div>


  </div>


</div>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is festival:</strong>
  <%= @show.is_festival %>
</p>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @show.begin_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @show.end_date %>
</p>

<p>
  <strong>Open to public:</strong>
  <%= @show.open_to_public %>
</p>

<p>
  <strong>Gallery:</strong>
  <%= @show.gallery_id %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>